version: "3.9"
services:
  railsapprabbitmq:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/my_app
    depends_on:
      - db
      - rabbitmq
      - maildev
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
volumes:
  ruby:

